/**
 * Offline common-password denylist (rule DATA, not logic). This is the curated
 * set of the most-abused passwords that registration rejects outright, without a
 * network call — the cheap first layer before the online HIBP breach check
 * (`auth/breachCheck.ts`) covers the long tail. Edit this list to retune the
 * denylist; the policy logic in `auth/passwordPolicy.ts` never changes with it.
 *
 * Entries are compared case-insensitively (the policy lowercases the candidate),
 * so list each only once in lowercase. Keep it to genuinely ubiquitous choices —
 * it is a denylist of the worst offenders, not a dictionary.
 */

/** The lowercase common-password denylist. */
export const COMMON_PASSWORDS: readonly string[] = [
  '123456',
  '123456789',
  '12345678',
  '1234567890',
  '12345',
  '1234567',
  'password',
  'password1',
  'password123',
  'passw0rd',
  'qwerty',
  'qwerty123',
  'qwertyuiop',
  'abc123',
  'abcd1234',
  'a1b2c3d4',
  '111111',
  '000000',
  '123123',
  '654321',
  'iloveyou',
  'admin',
  'admin123',
  'administrator',
  'welcome',
  'welcome1',
  'welcome123',
  'letmein',
  'monkey',
  'dragon',
  'sunshine',
  'princess',
  'football',
  'baseball',
  'superman',
  'batman',
  'master',
  'login',
  'starwars',
  'whatever',
  'trustno1',
  'changeme',
  'secret',
  'shadow',
  'michael',
  'jordan',
  'harley',
  'hunter2',
  'qazwsx',
  'zxcvbnm',
  'asdfghjkl',
  '1q2w3e4r',
  '1qaz2wsx',
  'q1w2e3r4',
  'p@ssw0rd',
  'p@ssword',
  'passwordpassword',
  'secureai',
  'cloudflare',
  'ninja',
  'computer',
  'samsung',
  'google',
  'photoshop',
  'maggie',
  'freedom',
  'flower',
  'hello123',
  'test123',
  'root',
  'toor',
  'pokemon',
  'soccer',
  'killer',
  'andrew',
  'thomas',
  'robert',
  'daniel',
  'jessica',
  'charlie',
  'michelle',
  'jennifer',
  'liverpool',
  'arsenal',
  'chelsea',
]
